
#define FILAMENT_ENCODER_DETECTION_LENGTH 2.357f //2.88
#define DISTANCE_FROM_SWITCH_TO_SAFEZONE 70.0f
#define DISTANCE_FROM_SWITCH_TO_Head 30.0f

#define E_ROTATION_DISTAMCE_T0 21.60  //mm
#define E_ROTATION_DISTAMCE_T1 21.81  //mm
#define E_ROTATION_DISTAMCE_T2 21.02  //mm
#define E_ROTATION_DISTAMCE_T3 20.66  //mm

#define EXTRUDER_DIRECTION 1

#define NumberOfTools 4

