
#define FILAMENT_ENCODER_DETECTION_LENGTH 2.88
#define DISTANCE_FROM_SWITCH_TO_SAFEZONE 120.0
#define DISTANCE_FROM_SWITCH_TO_Head 796.0
//#define E_ROTATION_DISTAMCE_13 21.0  //mm
//#define E_ROTATION_DISTAMCE_02 21.5  //mm

#define E_ROTATION_DISTAMCE_T0 21.60  //mm
#define E_ROTATION_DISTAMCE_T1 21.81  //mm
#define E_ROTATION_DISTAMCE_T2 21.02  //mm
#define E_ROTATION_DISTAMCE_T3 20.66  //mm

#define EXTRUDER_DIRECTION 1

#define NumberOfTools 4

